version: 0.2
env:
  parameter-store:
    username: /user/name
    password: /pass/word
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - pip install --upgrade awscli==1.18.17
      - docker login --username $username --password $password
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 382938247451.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=382938247451.dkr.ecr.us-east-1.amazonaws.com/sample
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"hello-world","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      
artifacts:
    files: imagedefinitions.json
